### ISSUE TITLE
stash push step 0 usage complaint

### ISSUE THREAD

**Issue by mbstrange2** [cornell-brg/mflowgen#50]
Hi Chris,

It seems that when I want to stash my step 0 of an mflowgen graph, I get the usage error instead of it actually stashing the step. My intuition says this is an unchecked corner case. ![This screenshot](https://user-images.githubusercontent.com/46541870/82242252-66a7c500-98f2-11ea-9f76-e5ca9d1353a0.png) shows the bug in action :).

**Comment by ctorng** [comment]
Should be fixed now
