### ISSUE TITLE
gdsmerge halts make job

### ISSUE THREAD

**Issue by steveri** [cornell-brg/mflowgen#56]
PROBLEM
Every time my make job hits an mflowgen `gdsmerge` step ("`mentor-calibre-gdsmerge`"), it halts and waits for user input, requiring manual intervention. I have to foreground the job, then hit a few carriage returns, then background the job again, to make it continue:
```
% cd $mflowgen/full_chip
% make >& make.log &
# (twelve hours later)
% jobs
[1]+  Stopped     make &>make.log
% tail make.log
# (halted in gdsmerge)
% fg; <cr><cr><cr>; bg
[1]+  Running     make &>make.log
```

POSSIBLE SOLUTION
I tracked the problem to the "`calibredrv`" command in `mflowgen-run`:
```
calibredrv -a layout ... 2>&1 | tee merge.log
```

I was able to duplicate the problem by simply doing "`calibre -h &`" at my command prompt. The subsequent "jobs" command says "Stopped," indicating that the job has hanged.
```
% calibredrv -h 2>&1 | tee merge.log &
% jobs
[1]+  Stopped     calibredrv -h 2>&1 | tee merge.log
```

By trial and error I found two ways to avoid the problem. Here, the "jobs" command says "Done," as it should, instead of "Stopped."
```
# Fix alternative 1: pipe something in from stdin
% echo "" | calibredrv -h 2>&1 | tee merge.log &
% jobs
[1]+  Done     echo "" | calibredrv -h 2>&1 | tee merge.log

# Fix alternative 2: use nohup
nohup calibredrv -h 2>&1 | tee merge.log &
% jobs
[1]+  Done     nohup calibredrv -h 2>&1 | tee merge.log
```

Can one of these maybe be the default behavior for this step?

**Comment by alexcarsello** [comment]
I ran gdsmerge recently and did not encounter this. What is the job?

**Comment by steveri** [comment]
Example:
```
% cd mflowgen/full_chip/14-tile_array/1-Tile_PE
% make >& make.log &
# [halts silently in gdsmerge stage after 3-4 hours]
```
Note I'm pretty sure you only see this behavior if the job is running in the background. That is,

`make >& make.log`

should work just fine I think but

`make >& make.log &`

halts as soon as the `calibredrv` command is encountered.

It's possible that this is something unique to my environment. **But, again, you should be able to test /duplicate the problem very quickly** by doing

`calibredrv -h &`

and see if the job completes on its own (all it's supposed to do is print the help message and exit). In my shell, this command halts until you manually foreground it and hit some carriage returns.

**Comment by steveri** [comment]
FIXED by pull https://github.com/cornell-brg/mflowgen/pull/57 "use echo -pipe to fix calibredrv bug."
Thanks, everybody!
