### ISSUE TITLE
maybe some typo inside enc.tcl 

### ISSUE THREAD

**Issue by curliph** [cornell-brg/mflowgen#82]
step :  cadence_innovus_debug_calibre
file: enc.tcl
test env: CentOS6 

typo:
  seems all reference to system vars CALIBRE_HOME/MGC_HOME should be like:  $env(CALIBRE_HOME) and $env(MGC_HOME)
if not,  tcl return fail.

**Comment by curliph** [comment]
Updated:

```
  if {![info exists $env(CALIBRE_HOME)] || $env(CALIBRE_HOME)==""} {

    if {![file exists [exec which calibre]]} {
      puts "Tool calibre not found. Calibre interface NOT loaded."
      return
    }

    if {[info exists $env(MGC_HOME)]} {
      set CALIBRE_HOME $env(MGC_HOME)
    } else {
      set CALIBRE_HOME \
        [join [lrange [split [exec which calibre] /] 0 end-2] /]
    }
  }

  set etclf [file join $env(CALIBRE_HOME) lib cal_enc.tcl]

  if {![file readable $etclf]} {
    puts "Could not find Calibre initialization files."
    puts "Calibre interface not loaded."
    return
  }

  if {[catch {source $etclf} msg]} {
    puts "ERROR while loading Calibre interface: $msg"
  }
}

load_calibre

```

**Comment by ctorng** [comment]
It's actually not a typo for "info exists" commands:

- https://wiki.tcl-lang.org/page/info+exists
- https://stackoverflow.com/questions/9406940/tcl-info-exists

This mistake has been made before (actually in this file)... =)

I am pretty sure it is correct as it is, and I don't think it runs if you use "$env". I will close this, but feel free to reopen it if it is wrong.
